### ISSUE TITLE
v2.3.3 breaks Play's JPA implementation

### ISSUE THREAD

**Issue by mkurz** [schaloner/deadbolt-2-java#7]
I just upgraded to deadbolt-2-java `v2.3.3` (from `v2.3.2`).
Also I am using JPA/Hibernate.

### The Problem
I have a controller with a `@Restrict(@Group("mygroup"))` annotation. Inside this controller there is an action method which calls `play.db.jpa.JPA.em()` to retrieve the current hibernate entity manager. Starting with `v2.3.3` I get following exception:
```
Execution exception[[RuntimeException: No EntityManager bound to this thread. Try to annotate your action method with @play.db.jpa.Transactional]]
```
### The Cause
After some research I am pretty sure I know what's the problem:

First you should know that Play's JPA implemenation [puts the entity manager](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L173) into the [current HTTP context args](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L67-L72) (if there is a HTTP context, which is `true` in our case), so we can retrieve it [from there](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L47-L49).
After an action method (and it's annotations) are finished, the entity manager [gets removed](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L224) from the HTTP context args.

The problem is now that you [create and return a new `Promise`](https://github.com/schaloner/deadbolt-2-java/blob/2.3.x/code/app/be/objectify/deadbolt/java/actions/RestrictAction.java#L52-L99) from your `RestrictAction`, so the action method inside the controller itself [gets called](https://github.com/schaloner/deadbolt-2-java/blob/2.3.x/code/app/be/objectify/deadbolt/java/actions/RestrictAction.java#L88) **at later point in time**, which means the entity manager [gets set to `null`](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L223-L225) **before** the action method's code runs.

I hope you understand my description, if you need more information let me know.

**Comment by mkurz** [comment]
To simplify the problem create following simple project:

* run `activator new` and choose`play-java`.
* Copy these [VerboseActionFirst.java](https://gist.github.com/mkurz/442526fb670de545eca6) and [VerboseActionSecond.java](https://gist.github.com/mkurz/0a76c8a9cd56a42fd629) into `app/controllers/`.
* Replace the `app/controllers/Application.java` file with [this one](https://gist.github.com/mkurz/317806db204f4a411978).
* Run the project via `activator run`.

You should see the exception now.

**Comment by mkurz** [comment]
One more thing (I didn't test): In case `getSubject(...)` within a custom `DeadboltHandler` also would use JPA to retrieve the subject, the bug would occur in such a case too, because `getSubject` also [gets called in a later point in time](https://github.com/schaloner/deadbolt-2-java/blob/2.3.x/code/app/be/objectify/deadbolt/java/actions/RestrictAction.java#L57-L58) because it's inside the deferred `Promise` code. I didn't test this, but I am pretty sure these would fail too.

**Comment by schaloner** [comment]
I'm thinking I may have to create an extension as a separate module, and explicitly manage the transactional scope.   I'll try to get a prototype out later.

**Comment by mkurz** [comment]
@schaloner There is one more thing I want to mention, just for clarification:
Please also make sure that it's safe to access `play.db.jpa.JPA.em()` not just from within an action method, but also from within any annotation that runs **after** `@Restrict` (or any other deadbolt annotation). We, for example, use custom annotations that run after `@Restrict` to set hibernate filters, which means we also have to access the entity manager from within these annotations' action code.
Thanks!

**Comment by schaloner** [comment]
@mkurz I've put together a small test that works, but it's a clone of the JPA class with onRedeem() used to close the em() in place of the finally.  I'm going to write the module extension based on this, but if you want to take a look at the existing code I can mail it to you.

**Comment by schaloner** [comment]
@mkurz Solution proposal is at https://gist.github.com/schaloner/082108f5f0dcc76fd64b

AsyncTransactional would replace the Play's Transactional annotations.
AsyncTransactionalAction then hooks into DeadboltJPA, which closes entity managers [when the promise redeems](https://gist.github.com/schaloner/082108f5f0dcc76fd64b#file-deadboltjpa-java-L143-L148) instead of in a finally block.

**Comment by mkurz** [comment]
@schaloner The proposal looks alright, I can do some testing when I find some time.
Wouldn't it make sense to get these changes upstream into the Play project itself?

**Comment by schaloner** [comment]
There's an issue here which is somewhat related: https://github.com/playframework/playframework/pull/2042

I'll write this up for the Play team and see what they come back with.

There will be a snapshot version of the fix available this evening.

**Comment by mkurz** [comment]
Thanks!
I was reading through playframework/playframework#2042 - do you think after applying your proposed fix we could revert the changes in Play merged via playframework/playframework#2042? [Changing](https://github.com/playframework/playframework/pull/2042/files#diff-3df74e4be1bfca587af8c3ee4bf84152R18) `JPA.withTransactionAsync` to `JPA.withTransaction`  would not be necessary anymore - or am I wrong?

**Comment by schaloner** [comment]
I think that would be possible.  Once this has been tested - I'll ask Johan Dahlberg to test too - I'll prep a pull request.

**Comment by mkurz** [comment]
Nice, thank you!

**Comment by johdah** [comment]
@schaloner nice!

**Comment by schaloner** [comment]
@mkurz @johdah game on.  I've committed an initial version (see https://github.com/schaloner/async-transactions) and it's available via sonatype so you can just add

    "be.objectify" %% "async-transactions" % "1.0-SNAPSHOT" 

to your build.sbt.

After that, change your @Transactional annotations to @AsyncTransactional annotations (the parameters remain the same) and you should be good to go.

**Comment by mkurz** [comment]
>Actions (interceptors) are applied in the order of annotation specification, so to ensure the transaction is present for subsequent actions this must be the first annotation specified for a type or method.

Are you sure? I thought the order of annotations isn't guaranteed...

**Comment by johdah** [comment]
Nice, I will test it tomorrow when I am back at the office.

**Comment by schaloner** [comment]
Pretty sure - I get consistent results. If I put a Restrict first, it fails every time; if I put AsyncTransactional first, it works every time.

However, testing shows I'm wrong I have a cunning back-up plan.

**Comment by johdah** [comment]
I can't resolve the async-transactions dependency. Is it published at the same place as deadbolt or do I need to publish it locally? Or doesn't it support scala 2.11.x?

**Comment by schaloner** [comment]
Ah, you'll need to add 

    resolvers += Resolver.sonatypeRepo("snapshots")

to your build.sbt

**Comment by johdah** [comment]
I have started testing it but I had to recompile it with Java 7 (depend on it) and publish it locally to get it to work.

**Comment by schaloner** [comment]
Great, thanks.

I'll recompile it with Java 6 and publish it again later.

**Comment by johdah** [comment]
I have only tested it on one of my issues but that issue looks like it is solved. I will make a test release and deploy it to our test server later today and test it more deeply.

**Comment by mkurz** [comment]
About the annotations ordering: I could not find any specification that the order is preserved. 
Play [is using](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L34) `java.lang.reflect.Method.getDeclaredAnnotations()` to retrieve the annotations - it's [documentation](http://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html#getDeclaredAnnotations--) says nothing about the ordering (also see [this answer](http://stackoverflow.com/questions/16756291/is-java-annotation-order-persistent/16756356#16756356) from SO). Also I couldn't find any clear statement anywhere on the internet...
However it seems that at least when using the Oracle JVM the order gets preserved. Which means the java compiler preserves the order when generating the class files and `getDeclaredAnnotations()` doesn't use a `HashMap` or similiar in the background... I tested it and also worked for me, so I think we are fine right now - at least until somebody raises a bug about this concern..

**Comment by mkurz** [comment]
@schaloner Will you also make a PR with the fix against the Play framework repo?

**Comment by schaloner** [comment]
I'll code up the back-up plan, and then both cases are covered.

I'll comment in https://github.com/playframework/playframework/pull/2042 and take it from there.  It would be nice to have this in the core.

**Comment by johdah** [comment]
Could this error be caused by this fix?

"Caused by: org.hibernate.AssertionFailure: collection [models.organizations.Company.contracts] was not processed by flush()"

I haven't seen this error before.

**Comment by mkurz** [comment]
@schaloner I am testing right now, I'll let you know when I am finished.

**Comment by schaloner** [comment]
@johdah I wouldn't have thought so, because the fix only changes where the EM is closed, not how it's made available.  In fact, AsyncJPA delegates to play.db.jpa.JPA to actually manage the EMs.

Can you post the full stack trace?

**Comment by johdah** [comment]
I have restarted my computer since so I lost the log, but I haven't seen the error since. I will post it if I run into it again.

**Comment by schaloner** [comment]
@johdah I've republished the snapshot using Java 6.

**Comment by johdah** [comment]
@schaloner Nice!

**Comment by mkurz** [comment]
I did a code review and some testing now.

The solution "only" works fine as long as there is a `Http.Context` available. This of course should always be the case when you use `@AsyncTransactional` on a controller or an action method (because they are always called from an HTTP request).

**But** as soon somebody uses `AsyncJPA.withTransactionAsync(...)` somewhere where no `Http.Context` is available, e.g. in `Global.onStart()`, then the solution will (better: "could") fail and in the worst case there will be a memory leak.
Why? You now call `AsyncJPA.bindForCurrentThread(...)` from within [`.onFailure(...)`](https://github.com/schaloner/async-transactions/blob/3dbc11a5a97b0f46168132f54b374ebc45d700ae/code/app/be/objectify/as/AsyncJPA.java#L121) and [`.onRedeem(...)`](https://github.com/schaloner/async-transactions/blob/3dbc11a5a97b0f46168132f54b374ebc45d700ae/code/app/be/objectify/as/AsyncJPA.java#L130) on the `F.Promise`. A Play `F.Promise` is basically [a wrapper](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/java/play/libs/F.java#L528-L530) for a `scala.concurrent.Future`. (Play just [use the term `onRedeem` instead of `onSuccess`](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/core/j/FPromiseHelper.scala#L94-L95)). When you now [have a look inside the Scala docs](http://docs.scala-lang.org/overviews/core/futures.html) you will find following passage:
> That said, we should now comment on when exactly the callback gets called. Since it requires the value in the future to be available, it can only be called after the future is completed. **However, there is no guarantee it will be called by the thread that completed the future or the thread which created the callback. Instead, the callback is executed by some thread, at some time after the future object is completed.** We say that the callback is executed eventually.

And thats a huge problem: Because when there is no `HTTP.Context`, `bindForCurrentThread(...)` [uses a `ThreadLocal` instead](https://github.com/playframework/playframework/blob/2.3.x/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L75). But, as described in the docs, `.onRedeem(...)` and `.onFailure(...)` could run in different threads, so they could access the wrong `ThreadLocal`, which means the Entity manager continues to exist inside another `ThreadLocal`, owned by another Thread (the Thread in which it got set in the first place). Memory leak!

**So what's a possible solution?**
Stricly use `@AsyncTransactional`on controllers and actions **ONLY** (which means there always is a `Http.Context` available) and **never ever ever** just call `AsyncJPA.withTransactionAsync(...)` (at least when you are not sure if there is a `Http.Context` available).

Maybe this should be pointed out in the README? Because the sense of the `@AsyncTransactional` is to be used together with a deadbolt annotations, I think this possible bug/memory leak is probably acceptable as long people know to not use `AsyncJPA.withTransactionAsync(...)` itself... What do you think?

Anyway, this is getting more interessing for the PR for the Play repo. Also there it should be documented to never call `play.db.JPA.withTransactionAsync(..)` itself but to always use  `play.db.JPA.withTransaction(..)` instead (because it doesn't use `.onRedeem(...)` and `.onFailure(...)`)

I hope you understand me :)

**Comment by mkurz** [comment]
BTW: I am off for today, maybe I have some time in the evening. Have a nice weekend!

**Comment by mkurz** [comment]
Maybe we can just make `withTransactionAsync` `private` or `protected`, so nobody calls it the wrong way? With a decenct comment... Also for the PR for the Play repo?

**Comment by schaloner** [comment]
It's a pity there isn't a call context which lives separately to but complements the HTTP context - this would me a more natural place for the args to exist.

For now, at least, I think it's enough to document this restriction.

Thanks for all your work on this, it's very appreciated!

**Comment by mkurz** [comment]
@schaloner I made [some comments](https://github.com/schaloner/async-transactions/commit/3dbc11a5a97b0f46168132f54b374ebc45d700ae) on one of your commits.

I really would like to see this in the Play repo, if it's possible even before the first RC of Play 2.4.0 which is [just days or even hours](https://groups.google.com/d/msg/play-framework-dev/7S2163rUzLE/9D0AjdxmFR4J) away - so we wouldn't have to use `@AsyncTransactional` in Play 2.4.
@schaloner If you don't find time, I could start to work on a PR in my Play fork maybe on Sunday evening or by Monday morning at the latest. First I would revert playframework/playframework#2042 and then basically update Play's existing `withTransactionAsync` method with your changes. Then I would either make this method `protected` (or similar) so people don't use it the wrong way (IMHO this should not be a problem because 2.4 is a major release which can break backwards compatibility) or I would immediately throw an exception with a decent error message if there is no HTTP.Context available, so people already know during developing that they should use `withTransaction` in such cases instead.
What do you think? But of course I am also happy if you want to prepare a PR :smile:

**Comment by schaloner** [comment]
I've just made the changes based on your suggestion, and made the behaviour  more explicit.  It's committed and published.  I'm not going to have time to prep a PR today, but I should be able to get something out by tomorrow morning (I think we're both in CET right?).

**Comment by mkurz** [comment]
Go for it. I am based in Vienna. I don't find time til Monday morning probably.

**Comment by schaloner** [comment]
@mkurtz still haven't had time to do this, and I'll be unavailable all day.  If you have time, can you prep the PR?

**Comment by mkurz** [comment]
@schaloner OK, I will set up a PR within the next 2 hours.

**Comment by mkurz** [comment]
@schaloner PR got submitted: https://github.com/playframework/playframework/pull/4225
Please check, if you wish changes or enhancements let me know.

**Comment by schaloner** [comment]
Thanks. My availability just dropped off the bottom of the page for a couple of days.  I saw the PR was closed because of the deadlock issue - need to have another think about this.

**Comment by mkurz** [comment]
I opened another PR https://github.com/playframework/playframework/pull/4232 to at least get some changes merged which IMHO should have been there in the first place.
However this doesn't help us here, because James Roper made the `@Transactional` annotation [synchron in Play 2.4](https://github.com/playframework/playframework/commit/853f0cd97509b72843ff0ba09eb2b1a644948e2a#diff-3df74e4be1bfca587af8c3ee4bf84152R18) because of the deadlock issue. So we still would get the "No entity manager found" exception, because the `withTransaction` does again use the [`finally`](https://github.com/playframework/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L154) statement to clean up the em.

**Comment by mkurz** [comment]
I don't know what we can do about this, maybe you have to remove the `Promise`s again from your annotations?

**Comment by mkurz** [comment]
@schaloner Just that you know, my PR https://github.com/playframework/playframework/pull/4232, which originally targeted our problem, got merged.

**Comment by schaloner** [comment]
@mkurz I was just reading it now.

So, the question now is, can this issue ever be closed?  The JPA threading restriction seems to be a real tick in the hide of web scale asynchronicity!

**Comment by varungupta85** [comment]
Not sure if I am entitled to comment on this post but I have the same problem when I was trying to use Deadbolt with my Play application today and I came across this post. I was able to solve the problem using below code:

        @Override
	public Subject getSubject(Http.Context context) {
		try {
			return JPA.withTransaction(new Function0<Subject>() {
				@Override
				public Subject apply() throws Throwable {
					return the subject here
				}
			});
		} catch (Throwable exception) {
			return null;
		}
	}

Also, I observed that if I have @Transactional before @Restrict in the controller action, it somehow interferes with the functioning of @Transactional. Maybe because the transaction is closed in the getSubject method. But moving @Transactional after @Restrict solved that problem

**Comment by schaloner** [comment]
This is actually a generic error caused by the way transactions are closed by the play.db.jpa.JPA class.  

It's possible to fix this issue in Play 2.3 by using this [async transactions module](https://github.com/schaloner/async-transactions) - in Play 2.4, these changes have been patched into the main codebase.

However, the problem is one of deadlocks.  @jroper gives an explanation of the problem [here](https://github.com/playframework/playframework/pull/4225#issuecomment-92597680).

**Comment by johdah** [comment]
@schaloner You mean that Transactional is patched with what you do in AsyncTransactional in Play 2.4+?

**Comment by schaloner** [comment]
@johdah to a degree.  The play.db.jpa.Transactional annotation will trigger a [synchronous transaction](https://github.com/playframework/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/TransactionalAction.java#L16), whereas be.objectify.as.Async will trigger an [asynchronous transaction](https://github.com/schaloner/async-transactions/blob/master/code/app/be/objectify/as/AsyncTransactionalAction.java#L21).

 When the default implementation of JpaAPI#withTransactionAsync is explicitly used, the transaction is [closed asynchronously](https://github.com/playframework/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L171-L236).  Full details are in @mkurz's [pull request](https://github.com/playframework/playframework/pull/4225).

**Comment by johdah** [comment]
@schaloner but enough to solve the error causing the entity manager to be closed before the Action when using Deadbolt.

**Comment by schaloner** [comment]
Yes, because 
- with synchronous transactions it isn't an issue
- with asynchronous transactions, asynchronous closing is required.

**Comment by mkurz** [comment]
@schaloner FYI:
Some news for my [comment](https://github.com/schaloner/deadbolt-2-java/issues/7#issuecomment-91488550) about annotations ordering: Just a few hours ago [a really good answer](http://stackoverflow.com/a/30222541/810109) was posted on stackoverflow: Regarding this answer `getDeclaredAnnotations()` indeed provides the annotations in a guaranteed order (at least in Java 8) :smile:

**Comment by schaloner** [comment]
@mkurz good info, thanks for the link.

**Comment by mkurz** [comment]
@schaloner Any news here?
Like mentioned in a comment above this is still an issue in Play 2.4 since `@Transactional` is now using a *synchron* transaction [starting with Play 2.4](https://github.com/playframework/playframework/commit/853f0cd97509b72843ff0ba09eb2b1a644948e2a#diff-3df74e4be1bfca587af8c3ee4bf84152R18). (Even) if we try to solve the problem by writing an own async-transaction annotation for Play 2.4 (like [you did](https://github.com/schaloner/async-transactions) for 2.3) which relies on `withTransactionAsync` instead, we have a chance to bump into the deadlock issue.
So is there a chance we can finally solve this issue without any side effects? @schaloner what's your cunning back-up plan you were talking about? :smile:

**Comment by schaloner** [comment]
The cunning back-up plan is to use EBean :-)

JPA, as far as I can see, is incompatible with non-blocking systems.  Since the information Deadbolt requires is read-only - unless you have something in your handler or subject that writes to the DB on access - the only feasible way to make this compatible is to use a non-transactional DB read.  Hence, EBean.

The deeper problem is that you're going to hit this problem throughout your codebase until you design it around the JPA em restrictions.

**Comment by schaloner** [comment]
The other alternative is to write a version which makes blocking calls until all DB interactions are complete, which is very very annoying.

**Comment by mkurz** [comment]
I am working on a patch which introduces the setting `deadbolt.java.blocking` (`false` by default) which allows you to control if deadbolt should be blocking or non-blocking. I did some testing with my fix and and works for me. I know you loose all the non-blocking functionallity, but to get JPA working with deadbolt, I don't see any other option.
I will set up a PR for discussion.

**Comment by mkurz** [comment]
(The problem I think is JDBC itself, as it just isn't designed to be asynchronous: http://mikemainguy.blogspot.co.at/2015/05/the-myth-of-asynchronous-jdbc.html)

**Comment by mkurz** [comment]
I set up #14 for discussion. @schaloner What do you think? I know it's not beautiful to return `Promise`'s which are not really `Promise`'s anymore, but we could document the `deadbolt.java.blocking` setting mentioning the JPA restrictions.

**Comment by schaloner** [comment]
Issue fixed in 2.4.1 - closing by request of OP.

See [#14](https://github.com/schaloner/deadbolt-2-java/pull/14) for further details.

**Comment by robguinness** [comment]
I am having a similar (if not identical) issue, and I came across this thread. I am trying to understand the status of this issue. The last comment indicates that the issue is fixed with v2.4.1 of deadbolt, but I am still seeing the problem. I am using v2.4.2 of play together with Hibernate. I added the setting deadbolt.java.blocking=true. Am I missing something still?

Here is the exception I'm getting:

```
Caused by: java.lang.RuntimeException: No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional
        at play.db.jpa.JPA.em(JPA.java:69) ~[play-java-jpa_2.11-2.4.2.jar:2.4.2]
        at models.FindHelper.getSession(FindHelper.java:32) ~[classes/:na]
        at models.FindHelper.<init>(FindHelper.java:26) ~[classes/:na]
        at models.User.getEmailUserFind(User.java:218) ~[classes/:na]
        at models.User.getUsernamePasswordAuthUserFind(User.java:107) ~[classes/:na]
        at models.User.findByUsernamePasswordIdentity(User.java:124) ~[classes/:na]
        at models.User.findByAuthUserIdentity(User.java:118) ~[classes/:na]
        at security.MyDeadboltHandler.getSubject(MyDeadboltHandler.java:56) ~[classes/:na]
        at be.objectify.deadbolt.java.cache.DefaultSubjectCache.apply(DefaultSubjectCache.java:53) ~[deadbolt-java_2.11-2.4.1.jar:2.4.1]
        at be.objectify.deadbolt.java.cache.DefaultSubjectCache.apply(DefaultSubjectCache.java:18) ~[deadbolt-java_2.11-2.4.1.jar:2.4.1]

**Comment by johdah** [comment]
@robguinness  Do you have your @Transactional annotation before you have a Deadbolt subject?

**Comment by ecagiral** [comment]
> The other alternative is to write a version which makes blocking calls until all DB interactions are complete, which is very very annoying. Even then, the contract of [Action](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/Action.java#L27) is such that it may run in a different thread to the controller block anyway.

Hey @schaloner, sorry for bothering after 5 years but I couldn't understand this one. Blocking line (maybeBlock()) only blocks the thread that calls DeadBolt action. But AbstractDeadboltHandler.getSubject() is already an async operation and will be handled by another thread. That means all DB interactions are not handled in single thread. Moreover if you receive N requests during your getSubject operation that means N threads will be in TIMED_WAITING state which may cause deadlock if your max thread count is limited.
